INSERT INTO shops VALUES
('action',	'Action'),
('ah',		'Albert Hein'),
('aldi',  'Aldi'),
('amazon',	'Amazon'),
('amazonde',  'Amazon DE'),
('aveve',  'Aveve'),
('blokker',	'Blokker'),
('bol',	    'Bol.com'),
('boupun',	'Bouwpunt'),
('branta',	'Brantano'),
('brico',	'Brico'),
('bridep',	'Brico Depot'),
('bruneau',	'Bruneau'),
('cg',		'Collect & Go (Colruyt)'),
('colora',	'Colora'),
('colshop',	'ColliShop'),
('coolblue', 'Coolblue'),
('cora',	'Cora'),
('crf',		'Carrefour'),
('dll',		'Delhaize'),
('dreamland',	'Dreamland'),
('eldi',	'Eldi'),
('fnac',	'Fnac'),
('fun',		'Fun'),
('gamma',	'Gamma'),
('hornbach', 	'Hornbach'),
('hubo', 	'Hubo'),
('intermar',  'Intermarche'),
('karwei',	'Karwei'),
('klium',	'Klium'),
('krefel',	'Krefel'),
('kruidvat',	'Kruidvat'),
('lidl',	'Lidl'),
('maisdm',	'Maison Du Monde'),
('makro',	'Makro'),
('match',  'Match'),
('medmar',	'Mediamarkt'),
('mrbric',  'Mr. Bricolage'),
('planit',	'Brico Planit'),
('praxis',	'Praxis'),
('sligro',  'Sligro'),
('standbkh', 'Standaard Boekhandel'),
('tomco',	'Tom & Co'),
('toonat',	'Toolnation'),
('torfs',	'Torfs'),
('vdborr',	'Vandenborre'),
('wink',	'Wink')
ON CONFLICT DO NOTHING;
